apiVersion: v1
kind: Service
metadata:
    name: pavanshivanandazuredevopskubernetes
spec:
    type: LoadBalancer
    ports:
    - port: 8000 
    selector:
        app: pavanshivanandazuredevopskubernetes